#!/system/bin/sh
# **************************************
# init.d script for Next kernel 
# **************************************

#***************************
# Cpu Freq & Governor Setting
#***************************
    # Gov = ondemand, performance, interactive, smartmax, smartmax_eps, intelliactive, gaming 
    #echo "ondemand" /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    #echo "ondemand" /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
    #echo "ondemand" /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
    #echo "ondemand" /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

    # Freq min = 51000, max = 1600000
    #echo "51000" /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
    #echo "1600000" /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

#*******************
#Sweep2Wake Setting
#*******************

	#enable=1, disable=0	
	#echo "0" > /sys/android_touch/sweep2wake
	#echo "9" > /sys/android_touch/s2w_register_threshold
	#echo "325" > /sys/android_touch/s2w_min_distance
	# Sweep direction
	#echo "1" > /sys/android_touch/s2w_allow_stroke
	#enable=1, disable=0	
	#echo "0" > /sys/android_touch/doubletap2wake    
	#echo "1300" > /sys/android_touch/s2w_double_tap_barrier_y
	#echo "150" > /sys/android_touch/s2w_double_tap_duration
	#echo "150" > /sys/android_touch/s2w_double_tap_threshold
	#enable=1, disable=0	
	#echo "0" > /sys/android_touch/pocket_detect

#*********************
# LED button
#*********************
	# Enable=1, disable=0
	#echo "0" > /sys/class/leds/button-backlight/slow_blink

	# Value Min=0 , Max=225
	#echo "225" > /sys/class/leds/button-backlight/button_brightness

#******************
# Touchscreen
#******************

	# Enable=1, disable=0 - for multitouch issue
        #echo "0" > /sys/android_touch/calibration_control

#*******************
# Audio Freq
#*******************
	# Enable this if playing music stutter
	#echo "204000" > /sys/module/snd_soc_tlv320aic3008/parameters/audio_min_freq

#*******************
# Cpu Freq Hard Cap
#*******************

	#echo "1200000" > /sys/module/cpu_tegra/parameters/cpu_user_cap

#******************
# CpuQuiet
#******************
	#To limit how much cpu online, min=1, max=4
	#echo "4" > /sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/max_cpus
	#echo "1" > /sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/min_cpus

#******************
# Mp Decision
#******************
    #To change those frequencies echo the cpu number + the frequency in khz. 
	# To verify [ cat /sys/kernel/tegra_mpdecision/conf/boost_freqs ]
	#echo "0 102000" > /sys/kernel/tegra_mpdecision/conf/boost_freqs
	#echo "1 102000" > /sys/kernel/tegra_mpdecision/conf/boost_freqs
	#echo "2 102000" > /sys/kernel/tegra_mpdecision/conf/boost_freqs
	#echo "3 102000" > /sys/kernel/tegra_mpdecision/conf/boost_freqs

	#To limit how much cpu online
	#echo "4" > /sys/kernel/tegra_mpdecision/conf/max_cpus
	#echo "1" > /sys/kernel/tegra_mpdecision/conf/min_cpus

#****************
# Frandom
#****************
 	
	# Script to launch frandom at boot by Ryuinferno @ XDA

	#insmod /system/lib/modules/frandom.ko
	#chmod 644 /dev/frandom
	#chmod 644 /dev/erandom
	#mv /dev/random /dev/random.ori
	#mv /dev/urandom /dev/urandom.ori
	#ln /dev/frandom /dev/random
	#chmod 644 /dev/random
	#ln /dev/erandom /dev/urandom
	#chmod 644 /dev/urandom

